import ConnectorDeratingCalculator from '../../../components/ConnectorDeratingCalculator';

export const metadata = {
  title: 'Connector Derating Calculator: Estimate Current Rating by Ambient Temperature',
  description:
    'Estimate a connector’s derated current rating for your actual operating ambient temperature, using the standard square-root derating approximation. Free tool.',
};

export default function ConnectorDeratingCalculatorPage() {
  return (
    <main className="tool-page">
      <h1>Connector Derating Calculator</h1>

      <p>
        Enter a connector’s rated current, the reference ambient it was tested at, its max rated
        temperature, and your actual operating ambient — this estimates how much current the
        connector can safely carry at your real-world temperature.
      </p>

      <ConnectorDeratingCalculator />

      <section className="tool-page-explainer">
        <h2>How this calculator works</h2>
        <p>
          Connector current ratings are almost always measured at a specific reference ambient
          temperature (often 20–30°C) and a specific allowable temperature rise. As ambient
          temperature climbs toward the connector’s max rated temperature, less of that thermal
          headroom is left for the heat generated by current flow, so the safe current has to drop.
          Because resistive heating scales with the square of current, most manufacturer derating
          curves — and this calculator — use a square-root relationship between remaining
          temperature headroom and derated current.
        </p>
        <p>
          For the full explanation of how to read a manufacturer’s actual derating curve, common
          mistakes, and a worked example, see{' '}
          <a href="/articles/how-to-read-connector-thermal-derating-curves/">
            How to Read Connector Thermal Derating Curves
          </a>{' '}
          and{' '}
          <a href="/articles/cable-temperature-ratings-current-derating-voltage-drop/">
            Cable Temperature Ratings, Current Derating & Voltage Drop
          </a>
          . (Double-check both slugs against Strapi before publishing — verify from the live site
          rather than assuming.)
        </p>
      </section>
    </main>
  );
}
